#' @importFrom checkmate assert_date
#' @importFrom checkmate assert_choice
#' @importFrom lubridate ymd
#' @importFrom lubridate dmy
#' @importFrom lubridate interval
#' @importFrom lubridate years
#' @importFrom lubridate period
#' @importFrom lubridate weeks
#' @importFrom lubridate days
